CREATE DATABASE LIBRARY;
USE LIBRARY;

CREATE TABLE ADMIN (
    USER_ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    CONTACT VARCHAR(10)
);

INSERT INTO ADMIN (USER_ID, NAME, PASSWORD, CONTACT)
VALUES ('USERNAME','USERNAME','PASSWORD','CONTACT');

CREATE TABLE BOOKS (
    BOOK_ID VARCHAR(50) PRIMARY KEY,
    CATEGORY VARCHAR(50),
    NAME VARCHAR(50),
    AUTHOR VARCHAR(50),
    COPIES VARCHAR(10)
);

-- INSERT YOUR BOOKS VALUES

CREATE TABLE STAFF (
    STAFF_ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(50),
    CONTACT VARCHAR(10)
);

-- INSERT YOUR STAFF VALUES
